### ISSUE TITLE
Initial Design

### ISSUE THREAD

**Issue by mbonig** [cdk-dev/cdk-training-email#1]
This needs initial design. Initial thoughts, from Edwin:

I recently followed a 7 day email series called “Blogging for devs” where you got every other day an email with information and a task to implement. I found that really enjoyable so I thought it might be a cool format for the advanced CDK course. Split up in multiple days and in the end after 7 days you have big application following best practices. Just wanted to share the idea and see how you like it.

**Comment by pgollucci** [comment]
commenting for updates

**Comment by EdwinRad** [comment]
Hi all,

I wrote a concept for this training and looking for feedback and topics to cover. 👍 
See the readme in this repo.

**Comment by pgollucci** [comment]
The content is good. The Formatting could use help.  Is it worth dicking with markdown or would a GH page or CDK.dev page make more sense ?

**Comment by pgollucci** [comment]
Link to the CDK Workshop don't just mention it, also I'd list it as a prereq?

In my experience most people learning CDK don't have issues with CDK, but with knowing TS/JS or Node/Yarn or VSCode, or AWS CLI or CFT.  CDK is actually pretty straight forward (minus the dep management).

**Comment by pgollucci** [comment]
Stack.of(), .node(), .defaultChild(), .find() are probably too advanced for the same training.

**Comment by EdwinRad** [comment]
Cool, thanks Philip. Great idea to include set up your environment and add some opinionated advice.
